version: "3"

services:
  vscode:
    platform: linux/amd64
    build: .
    volumes:
      - ../:/workspace
    environment:
      - TZ=
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: [ "zsh", "-c", "sleep infinity" ]